/**
 * @type object
 * List of sql keywords which supported by openSql
 **/

export default {
    OR: 'OR',
    IN: 'IN',
    AS: 'AS',
    BY: 'BY',
    ON: 'ON',
    TOP: 'TOP',
    FOR: 'FOR',
    END: 'END',
    ANY: 'ANY',
    SET: 'SET',
    AND: 'AND',
    ADD: 'ADD',
    ALL: 'ALL',
    NOT: 'NOT',
    ASC: 'ASC',
    USE: 'USE',
    JOIN: 'JOIN',
    EXEC: 'EXEC',
    NULL: 'NULL',
    DROP: 'DROP',
    ELSE: 'ELSE',
    LEFT: 'LEFT',
    CASE: 'CASE',
    WHEN: 'WHEN',
    WITH: 'WITH',
    DESC: 'DESC',
    CAST: 'CAST',
    LIKE: 'LIKE',
    THEN: 'THEN',
    FROM: 'FROM',
    CHECK: 'CHECK',
    LIMIT: 'LIMIT',
    RIGHT: 'RIGHT',
    COUNT: 'COUNT',
    ALTER: 'ALTER',
    ORDER: 'ORDER',
    UNION: 'UNION',
    INDEX: 'INDEX',
    TABLE: 'TABLE',
    GROUP: 'GROUP',
    WHERE: 'WHERE',
    INNER: 'INNER',
    UPDATE: 'UPDATE',
    SELECT: 'SELECT',
    DELETE: 'DELETE',
    MODIFY: 'MODIFY',
    COLUMN: 'COLUMN',
    OFFSET: 'OFFSET',
    UNIQUE: 'UNIQUE',
    BACKUP: 'BACKUP',
    HAVING: 'HAVING',
    CREATE: 'CREATE',
    VALUES: 'VALUES',
    IS_NULL: 'IS NULL',
    DEFAULT: 'DEFAULT',
    WITHOUT: 'WITHOUT',
    PERCENT: 'PERCENT',
    BETWEEN: 'BETWEEN',
    CASCADE: 'CASCADE',
    TO_DISK: 'TO DISK',
    COMMENT: 'COMMENT',
    STORAGE: 'STORAGE',
    NOT_NULL: 'NOT NULL',
    TRUNCATE: 'TRUNCATE',
    SET_NULL: 'SET NULL',
    DATABASE: 'DATABASE',
    RESTRICT: 'RESTRICT',
    DISTINCT: 'DISTINCT',
    TIME_ZONE: 'TIME ZONE',
    IF_EXISTS: 'IF EXISTS',
    PROCEDURE: 'PROCEDURE',
    NO_ACTION: 'NO ACTION',
    FULL_OUTER: 'FULL OUTER',
    REFERENCES: 'REFERENCES',
    CONSTRAINT: 'CONSTRAINT',
    IS_NOT_NULL: 'IS NOT NULL',
    INSERT_INTO: 'INSERT INTO',
    PRIMARY_KEY: 'PRIMARY KEY',
    FOREIGN_KEY: 'FOREIGN KEY',
    IF_NOT_EXISTS: 'IF NOT EXISTS',
    AUTO_INCREMENT: 'AUTO_INCREMENT'
}