/**
 * Map of sql keywords which supported by openSql
 * @param {Object}
 */
export default {
  IN: 'IN',
  SET: 'SET',
  USE: 'USE',
  NULL: 'NULL',
  DROP: 'DROP',
  WITH: 'WITH',
  FROM: 'FROM',
  CHECK: 'CHECK',
  INDEX: 'INDEX',
  TABLE: 'TABLE',
  CREATE: 'CREATE',
  DEFAULT: 'DEFAULT',
  WITHOUT: 'WITHOUT',
  COMMENT: 'COMMENT',
  NOT_NULL: 'NOT NULL',
  TRUNCATE: 'TRUNCATE',
  DATABASE: 'DATABASE',
  TIME_ZONE: 'TIME ZONE',
  IF_EXISTS: 'IF EXISTS',
  PRIMARY_KEY: 'PRIMARY KEY',
  CURRENT_DATE: 'CURRENT_DATE()',
  CURRENT_TIME: 'CURRENT_TIME()',
  CURRENT_USER: 'CURRENT_USER()',
  IF_NOT_EXISTS: 'IF NOT EXISTS',
  AUTO_INCREMENT: 'AUTO_INCREMENT',
};
