/**
 * @type object
 * Sql data types for create table
 */


export default {
    int: 'INT',
    bit: 'BIT',
    xml: 'XML',
    set: 'SET',
    text: 'TEXT',
    enum: 'ENUM',
    cidr: 'CIDR',
    real: 'REAL',
    year: 'YEAR',
    blob: 'BLOB',
    char: 'CHAR',
    json: 'JSON',
    date: 'DATE',
    inet: 'INET',
    time: 'TIME',
    uuid: 'UUID',
    bytea: 'BYTEA',
    ntext: 'NTEXT',
    point: 'POINT',
    nchar: 'NCHAR',
    float: 'FLOAT',
    money: 'MONEY',
    bigint: 'BIGINT',
    binary: 'BINARY',
    serial: 'SERIAL',
    double: 'DOUBLE',
    macaddr: 'MACADDR',
    decimal: 'DECIMAL',
    boolean: 'BOOLEAN',
    varchar: 'VARCHAR',
    tinyint: 'TINYINT',
    tsquery: 'TSQUERY',
    macaddr8: 'MACADDR8',
    tsvector: 'TSVECTOR',
    tinyblob: 'TINYBLOB',
    longblob: 'LONGBLOB',
    nvarchar: 'NVARCHAR',
    longtext: 'LONGTEXT',
    tinytext: 'TINYTEXT',
    smallint: 'SMALLINT',
    datetime: 'DATETIME',
    timestamp: 'TIMESTAMP',
    datetime2: 'DATETIME2',
    mediumint: 'MEDIUMINT',
    varbinary: 'VARBINARY',
    bigserial: 'BIGSERIAL',
    smallmoney: 'SMALLMONEY',
    mediumblob: 'MEDIUMBLOB',
    mediumtext: 'MEDIUMTEXT',
    varcharMax: 'VARCHAR(MAX)',
    smallserial: 'SMALLSERIAL',
    nvarcharmax: 'NVARCHAR(MAX)',
    varbinarymax: 'VARBINARY(MAX)',
    smalldatetime: 'SMALLDATETIME',
    datetimeoffset: 'DATETIMEOFFSET',
    characterVarying: 'CHARACTER VARYING'
}